import postgres from 'postgres';
process.loadEnvFile('../../apps/web/.env.local');
const sql = postgres(process.env.DATABASE_URL.trim(), { prepare:false, ssl:'require', max:3, connect_timeout:20, idle_timeout:10, onnotice:()=>{} });
const scalars=`SELECT (SELECT count(*) FROM launches)::int a,(SELECT count(*) FROM launches WHERE launched_at>now()-interval '24 hours')::int b,(SELECT count(DISTINCT creator) FROM launches)::int c,(SELECT min(launched_at) FROM launches) d,(SELECT count(*) FROM swaps)::int e,(SELECT count(*) FROM swaps WHERE block_time>now()-interval '24 hours')::int f,(SELECT count(DISTINCT trader) FROM swaps)::int g,(SELECT count(*) FROM balances WHERE balance_raw>0 AND holder<>'0x000000000000000000000000000000000000dead')::int h`;
const volume=`SELECT l.stock,st.symbol,st.decimals,coalesce(sum(s.amount_stock_raw),0)::numeric(40,0)::text a,coalesce(sum(s.amount_stock_raw) FILTER (WHERE s.block_time>now()-interval '24 hours'),0)::numeric(40,0)::text b FROM launches l JOIN stocks st ON st.address=l.stock LEFT JOIN swaps s ON s.token=l.token GROUP BY 1,2,3`;
const fees=`SELECT f.stock,st.symbol,st.decimals,sum(f.amount_raw)::numeric(40,0)::text a,sum(f.creator_raw)::numeric(40,0)::text b,sum(f.platform_raw)::numeric(40,0)::text c FROM fee_events f JOIN stocks st ON st.address=f.stock GROUP BY 1,2,3`;
const launches=`SELECT l.stock,st.symbol,count(*)::int a FROM launches l JOIN stocks st ON st.address=l.stock GROUP BY 1,2 ORDER BY 3 DESC`;
const stocksQ=`SELECT s.*,q.price_usd8,q.feed_updated_at FROM stocks s LEFT JOIN stock_quotes q ON q.stock=s.address ORDER BY s.symbol`;
const top=`WITH earned AS (SELECT l.creator,f.stock,sum(f.creator_raw) cr FROM fee_events f JOIN launches l ON l.token=f.token GROUP BY 1,2), ranked AS (SELECT creator,sum(cr) t FROM earned GROUP BY 1 ORDER BY t DESC LIMIT 10) SELECT e.creator,e.stock,s.symbol,s.decimals,e.cr::text,(SELECT count(*)::int FROM launches WHERE creator=e.creator) tk FROM earned e JOIN ranked r ON r.creator=e.creator JOIN stocks s ON s.address=e.stock ORDER BY r.t DESC`;

console.log('--- SOĞUK (bağlantı yok) ---');
let t=Date.now();
const r=await Promise.all([sql.unsafe(scalars),sql.unsafe(volume),sql.unsafe(fees),sql.unsafe(launches),sql.unsafe(stocksQ),sql.unsafe(top)]);
console.log('readStats deseni (6 sorgu, max:3):', Date.now()-t, 'ms');
console.log('  fees satırı:', r[2].length, '| top creators:', r[5].length);
console.log('--- ISINMIŞ ---');
t=Date.now();
await Promise.all([sql.unsafe(scalars),sql.unsafe(volume),sql.unsafe(fees),sql.unsafe(launches),sql.unsafe(stocksQ),sql.unsafe(top)]);
console.log('aynı desen tekrar:', Date.now()-t, 'ms');
await sql.end({timeout:5});
