#!/usr/bin/env node
/**
 * Writes packages/core/src/abi/stockpair.ts from the Foundry build, so the TypeScript side can never
 * describe a contract that no longer exists. Build first, then run from anywhere:
 *   pnpm abi                                  (forge build, then this script)
 *   node scripts/gen-abi.mjs --check          (CI: exit 1 when the checked-in file has drifted)
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const target = resolve(root, 'packages/core/src/abi/stockpair.ts');

// Export names are what every package imports; keep them stable across regenerations.
const CONTRACTS = [
  ['StockPairFactory', 'stockPairFactoryAbi'],
  ['StockPairHook', 'stockPairHookAbi'],
  ['StockPairRouter', 'stockPairRouterAbi'],
];

function readAbi(contract) {
  const path = resolve(root, `packages/contracts/out/${contract}.sol/${contract}.json`);
  if (!existsSync(path)) {
    console.error(`${path} is missing. Run \`forge build\` in packages/contracts first.`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(path, 'utf8'));
  if (!Array.isArray(abi) || abi.length === 0) {
    console.error(`${path} has no ABI.`);
    process.exit(1);
  }
  return abi;
}

const header =
  '// Generated by scripts/gen-abi.mjs from packages/contracts/out. Do not edit by hand:\n' +
  '// run `pnpm abi` after changing the contracts. CI fails when this file drifts from the build.\n';
const body = CONTRACTS.map(
  ([contract, name]) => `export const ${name} = ${JSON.stringify(readAbi(contract), null, 2)} as const;\n`,
).join('\n');
const generated = `${header}\n${body}`;

// Git may check the file out with CRLF on Windows; only the content counts.
const normalise = (text) => text.replace(/\r\n/gu, '\n');

if (process.argv.includes('--check')) {
  const current = existsSync(target) ? normalise(readFileSync(target, 'utf8')) : '';
  if (current !== generated) {
    console.error('packages/core/src/abi/stockpair.ts is out of date with the contracts. Run `pnpm abi` and commit it.');
    process.exit(1);
  }
  console.log('ABI up to date.');
} else {
  writeFileSync(target, generated);
  console.log(`Wrote ${target}`);
}
